// The control room's copy (D-045, tranche 205). Imported only inside the /sales/control route,
// so no other route's bundle carries it (UX gate #11).

/** The control room (D-045, tranche 205). Tom only. */
export const CONTROL_UI = {
  title: "חדר בקרה",
  hint: "מצב המערכות של המכירות, במבט אחד. רק תום רואה את הדף הזה.",
  /** completes UI.loadError: "לא הצלחנו לטעון את …" */
  loadError: "חדר הבקרה",
  generatedAt: (when: string) => `עודכן ${when}`,
  tile: {
    intake: "קליטת לידים",
    whatsapp: "קו הוואטסאפ ללידים",
    wake: "הודעות המשך",
    mirror: "סנכרון מ־Shopify",
    report: "דוח המכירות",
    radar: "רדאר הלקוחות הרדומים",
    settings: "יומן שינויי הגדרות",
  } as const,
  state: { green: "תקין", amber: "לבדוק", red: "תקלה" } as const,
  lastSuccess: (when: string) => `הצלחה אחרונה ${when}`,
  noSuccess: "עוד לא נרשמה הצלחה",
  lastChange: (when: string) => `שינוי אחרון ${when}`,
  /** an action the server sends that this copy does not know yet: by state */
  fallbackAction: (state: string) => (state === "green" ? "אין מה לעשות." : "בדקו את הלוג"),
  action: {
    ok: "אין מה לעשות.",
    never_ran: "עוד לא נרשמה ריצה. בדקו שמשימת ה־cron קיימת",
    wa_silent: "אף הודעה לא נמסרה ב־7 הימים האחרונים. בדקו את הקו.",
    intake_pulse_stale: "הדופק של Make לא הגיע יותר מיממה. בדקו את החיבור לפייסבוק ב־Make.",
    intake_poll_stale: "המשיכה מ־Meta לא הצליחה יותר מיממה. בדקו את הטוקן.",
    intake_unalerted: "יש לידים מהיומיים האחרונים בלי התראה. בדקו את שליחת המיילים.",
    intake_rejects: "לידים נדחו ביממה האחרונה. בדקו מה חסר בהם.",
    wa_off: "הקו לא מחובר. חסר מזהה המספר בשרת.",
    wa_failed: "הודעות נכשלו בשבוע האחרון. בדקו את סיבת הכישלון בלוג.",
    wa_test: "הקו במצב בדיקה: רק הטלפונים לבדיקה מקבלים הודעות באמת.",
    wake_no_runs: "עוד לא נרשמה ריצה. הריצות נרשמות מהעדכון הזה והלאה.",
    wake_error: "הריצה האחרונה נעצרה בשגיאה. בדקו את הלוג של השרת.",
    wake_quiet: "אין ריצה מוצלחת בשעה האחרונה. בדקו את משימת ה־cron.",
    wake_no_signer: "הודעות לא יצאו כי חסר שם חתימה. השלימו אותו בהגדרות.",
    wake_no_menu_file: "הודעות לא יצאו כי חסר קובץ תפריט. השלימו אותו בהגדרות.",
    wake_failed: "הודעות נכשלו בריצה האחרונה. בדקו את הלוג.",
    mirror_failed: "הריצה האחרונה נכשלה. בדקו את פירוט השגיאה.",
    mirror_stale: "אין ריצה מוצלחת יותר מ־30 שעות. בדקו את משימת ה־cron.",
    mirror_exceptions: "יש חריגים פתוחים. עברו עליהם.",
    report_failed: "הריצה האחרונה נכשלה. בדקו את פירוט השגיאה.",
    report_stale: "אין עדכון מוצלח בשעתיים האחרונות. בדקו את משימת ה־cron.",
    report_full_stale: "הדוח המלא לא נבנה יותר מיממה.",
    radar_stale: "הרדאר לא רץ יותר מ־30 שעות. בדקו את משימת ה־cron.",
  } as Record<string, string>,
  // facts, one short line each
  intakeMode: (mode: string) => (mode === "make" ? "מסלול: Make" : "מסלול: משיכה מ־Meta"),
  lastLead: (when: string) => `ליד אחרון ${when}`,
  leads24h: (n: number) => `${n} לידים ב־24 השעות האחרונות`,
  pulse: (mode: string, when: string) => (mode === "make" ? `דופק אחרון ${when}` : `משיכה מוצלחת אחרונה ${when}`),
  rejects24h: (n: number) => `${n} נדחו ב־24 שעות`,
  unalerted48h: (n: number) => `${n} בלי התראה ב־48 שעות`,
  waMode: { live: "פעיל: כל ליד מקבל הודעות", test: "מצב בדיקה", off: "לא מחובר" } as Record<string, string>,
  waWindow: "7 הימים האחרונים",
  waStatus: { sent: "נשלחו", delivered: "נמסרו", read: "נקראו", failed: "נכשלו", dry_run: "הרצה יבשה" } as Record<string, string>,
  optOuts: (total: number, week: number) => `ביקשו להפסיק: ${total} בסך הכל, ${week} השבוע`,
  templateApproval: "אישור התבניות ב־Meta: לא נשמר",
  wakeLast: (when: string) => `ריצה אחרונה ${when}`,
  wakeCounts: (considered: number, sent: number, dry: number, failed: number) =>
    `נבדקו ${considered} · נשלחו ${sent} · יבש ${dry} · נכשלו ${failed}`,
  wake24h: (runs: number, sent: number) => `${runs} ריצות ו־${sent} הודעות ב־24 שעות`,
  wakeSkipped: "דילוגים ב־24 שעות",
  // the wake job's skip reasons (gt-factory-os wake.ts), in words; an unknown one shows as sent
  skipReason: {
    no_signer: "חסר שם חתימה",
    no_menu_file: "חסר קובץ תפריט",
    no_menu: "לא נשלח תפריט ראשון",
    no_name: "אין שם לפנייה",
    already_claimed: "כבר נשלח",
    state_changed: "המצב השתנה",
    not_due: "עוד לא הזמן",
    outside_slot: "מחוץ לשעות השליחה",
    within_48h: "פחות מ־48 שעות מהקודמת",
    already_sent_today: "כבר נשלחה היום",
    not_eligible: "ההודעה הראשונה לא נמסרה",
    opted_out: "ביקשו להפסיק",
    ordered: "כבר הזמינו",
    replied: "ענו לנו",
    waiting_for_customer: "מחכים ללקוח",
    staff_wrote_within_24h: "כתבנו להם ב־24 שעות",
    sequence_complete: "הרצף הסתיים",
    step_already_sent: "השלב כבר נשלח",
    marketing_cap_retry_later: "מגבלת שיווק של Meta, ננסה שוב",
    no_such_step: "אין שלב כזה",
  } as Record<string, string>,
  remove: "הסרה",
  wakeError: (msg: string) => `שגיאה: ${msg}`,
  mirrorLast: (kind: string, status: string) => `ריצה אחרונה: ${kind} · ${status}`,
  openExceptions: (n: number) => (n === 0 ? "אין חריגים פתוחים" : `${n} חריגים פתוחים`),
  reportLast: (kind: string, status: string) => `ריצה אחרונה: ${kind} · ${status}`,
  reportFull: (when: string) => `דוח מלא אחרון ${when}`,
  radarCounts: (flagged: number, orgs: number) => `${flagged} מתוך ${orgs} עסקים סומנו לבדיקה`,
  settingsRecent: "שינויים אחרונים",
  settingsNone: "אין עדיין שינויים.",
  technicalTitle: "הגדרות טכניות",
  testPhonesTitle: "טלפונים לבדיקה",
  testPhonesHint: "כשהקו במצב בדיקה, רק המספרים האלה מקבלים את ההודעות האוטומטיות באמת.",
  testPhonesEmpty: "אין טלפונים לבדיקה.",
  testPhoneNew: "מספר חדש",
  testPhoneAdd: "הוספה",
  testPhoneRemove: (p: string) => `הסרת ${p}`,
  testPhoneBad: "כתבו מספר ישראלי, למשל 050-1234567",
  testPhonesSave: "שמירת הטלפונים",
  intakeModeTitle: "מסלול הקליטה",
  intakeModeReadOnly: "לקריאה בלבד. כדי לשנות את המסלול, פנו לצוות הפיתוח.",
  intakeModeValue: (mode: string | null) => (mode === "make" ? "Make מעביר את הלידים" : mode === "poll" ? "משיכה ישירה מ־Meta" : "לא הוגדר"),
  intakeModeChanged: (when: string) => `שונה ${when}`,
  intakePulseExpected: (v: string) => (v === "hourly" ? "דופק צפוי: כל שעה" : `דופק צפוי: ${v}`),
} as const;

/** Settings keys as a manager names them, for the control room's settings log. */
export const SETTING_KEY_LABELS: Record<string, string> = {
  whatsapp_quick_messages: "הודעות מהירות",
  response_time: "זמני תגובה",
  lead_journey_signers_by_email: "שמות חתימה",
  lead_menus: "קובצי תפריט",
  queue: "צורת התור",
  lost_reasons: "סיבות אבוד",
  lead_journey_test_phones: "טלפונים לבדיקה",
  sla_hours: "זמן תגובה (ישן)",
  whatsapp_templates: "תבניות WhatsApp (ישן)",
};
